/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface-variant": "#45474c",
        "on-tertiary-fixed-variant": "#564427",
        "surface-container-low": "#f5f3f4",
        "on-secondary-fixed": "#0b1c30",
        "primary-container": "#1e293b",
        "on-primary-container": "#8590a6",
        "secondary": "#505f76",
        "inverse-surface": "#303032",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#a38c6a",
        "primary": "#091426",
        "tertiary-fixed": "#fadfb8",
        "surface-variant": "#e4e2e3",
        "secondary-container": "#d0e1fb",
        "on-surface": "#1b1b1d",
        "background": "#fbf8fa",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-fixed-dim": "#ddc39d",
        "primary-fixed-dim": "#bcc7de",
        "tertiary-container": "#35260c",
        "on-secondary-container": "#54647a",
        "on-primary-fixed": "#111c2d",
        "on-tertiary-fixed": "#271902",
        "on-error-container": "#93000a",
        "inverse-primary": "#bcc7de",
        "inverse-on-surface": "#f3f0f2",
        "outline": "#75777d",
        "surface-tint": "#545f73",
        "on-secondary": "#ffffff",
        "surface-container": "#f0edef",
        "surface-container-high": "#eae7e9",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1b1d",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3c475a",
        "surface": "#fbf8fa",
        "primary-fixed": "#d8e3fb",
        "surface-bright": "#fbf8fa",
        "tertiary": "#1e1200",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e4e2e3",
        "secondary-fixed": "#d3e4fe",
        "on-error": "#ffffff",
        "outline-variant": "#c5c6cd",
        "surface-dim": "#dcd9db",
        "brand-blue": "#3b82f6",
        "brand-navy": "#1e293b",
        "brand-slate": "#64748b"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "section-gap-mobile": "64px",
        "grid-margin": "24px",
        "grid-gutter": "24px",
        "section-gap-desktop": "120px",
        "max-width": "1200px",
        "base": "8px"
      },
      "fontFamily": {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "display": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-code": ["14px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
